### ISSUE TITLE
메인 화면 마크업

### ISSUE THREAD

**Issue by jopopcorn** [euphony-io/check-in-speaker#10]
## TODO
* 디자인한 메인 화면(`MainActivity`)을 마크업 해주세요!
* 레이아웃은 가능하면 `ConstraintLayout`으로 해주시고, 너무 어렵다면 편하신 레이아웃으로 작업하셔도 됩니다.
* 작업 도중 궁금한 사항이나 어려운 점은 [디스커션](https://github.com/euphony-io/check-in-speaker/discussions/5)에 올려주시면 같이 해결하도록 하겠습니다!

## 참고 자료
피그마 링크는 슬랙 DM으로 보내드릴 예정입니다.

<img width="1095" alt="speaker_기본_배치" src="https://user-images.githubusercontent.com/35393459/134714973-8b44b036-4d76-4b4c-a676-bbd0e85d9a2c.png">

**Comment by designe** [comment]
화면이 깔끔하고 예쁘네요!
본인의 전화번호를 입력하면 개인안심번호를 바로 만들어서 보여주는건가요?
개인안심번호를 알려주는 API 같은 것을 쓰시는건가요? ㅎㅎ 궁금하네요

**Comment by jopopcorn** [comment]
@designe 감사합니다!! 😁 개인안심번호 API는 제공되지 않아서 팀에서 안심번호 변환 로직을 간단하게 만들어보려고 합니다!

**Comment by HACore** [comment]
[체크인 시작/종료에 따라 소리 크기 조절](https://github.com/euphony-io/check-in-speaker/discussions/1#discussioncomment-1383283) 기능이 구현된다면 `음성 데이터로 체크인하기 위해 볼륨을 크게 키워주세요` 텍스트는 삭제하는게 맞을까요?

**Comment by jopopcorn** [comment]
> [체크인 시작/종료에 따라 소리 크기 조절](https://github.com/euphony-io/check-in-speaker/discussions/1#discussioncomment-1383283) 기능이 구현된다면 `음성 데이터로 체크인하기 위해 볼륨을 크게 키워주세요` 텍스트는 삭제하는게 맞을까요?

앗 네네 삭제하는 게 좋을 것 같네요!!

**Comment by psh2849** [comment]
> [체크인 시작/종료에 따라 소리 크기 조절](https://github.com/euphony-io/check-in-speaker/discussions/1#discussioncomment-1383283) 기능이 구현된다면 `음성 데이터로 체크인하기 위해 볼륨을 크게 키워주세요` 텍스트는 삭제하는게 맞을까요?

아니면 체크인 버튼을 클릭하면 볼륨이 자동 조절된다고 쓸까요??

**Comment by HACore** [comment]
> 아니면 체크인 버튼을 클릭하면 볼륨이 자동 조절된다고 쓸까요??

이것도 좋은 방법이네요! `체크인 시 볼륨이 자동 조정됩니다` 이런식으로 적으면 될까요?

**Comment by jopopcorn** [comment]
> > 아니면 체크인 버튼을 클릭하면 볼륨이 자동 조절된다고 쓸까요??
> 
> 이것도 좋은 방법이네요! `체크인 시 볼륨이 자동 조정됩니다` 이런식으로 적으면 될까요?

넵넵 문구 아주 좋습니다 ㅎㅎ
