### ISSUE TITLE
방문 기록 화면 마크업

### ISSUE THREAD

**Issue by jopopcorn** [euphony-io/check-in-speaker#13]
**Is your feature request related to a problem? Please describe.**
- 방문 기록 화면 xml을 작업해주세요!
- `VisitRecordActivity`를 미리 생성해 둘테니, `activity_visit_record.xml`에서 작업해주시면 됩니다.

**Describe the solution you'd like**
아래 스크린샷을 참고해서 화면 구성을 해주시면 됩니다.
위의 상단바는 `Toolbar`를 배치하셔도 되고 간단하게 하고 싶으면 왼쪽에 화살표 버튼을 배치해주시고, 가운데에는 텍스트뷰를 배치하면 됩니다.
그 아래에는 리싸이클러뷰를 배치하면 됩니다. 글씨 크기와 색상을 참고하려면 [피그마](https://www.figma.com/file/0e7hUwdXmSIhoJmresxEQj/Euphony-Check-in-Speaker?node-id=0%3A1) 링크 확인하시면 됩니다!

**Additional context**
<img width="415" alt="스크린샷 2021-09-28 오전 12 22 25" src="https://user-images.githubusercontent.com/35393459/134937841-8c06b375-a3a9-4677-a480-4ca144c9c3a2.png"/>

**Comment by designe** [comment]
피그마는 UX 디자이너들이 엄청 선호하는 도구던데 잘 사용하시는군여!! 멋집니다 👍 
피그마로 협업도 편리한 것 같더라구요. ㅎㅎ 한번 유포니 멘티 대상 피그마 사용 사례 세미나 해보시는건 어떨까여 ㅋㅋ

**Comment by psh2849** [comment]
리스트의 각 항목마다 구분이 가게끔 항목의 아래쪽에 옅은 선 같은게 있으면 더 좋을 것 같습니다!

**Comment by jopopcorn** [comment]
> 피그마는 UX 디자이너들이 엄청 선호하는 도구던데 잘 사용하시는군여!! 멋집니다 👍
> 피그마로 협업도 편리한 것 같더라구요. ㅎㅎ 한번 유포니 멘티 대상 피그마 사용 사례 세미나 해보시는건 어떨까여 ㅋㅋ

ㅋㅋㅋㅋㅋㅋ 저도 아주 간단한 사용법만 알고 있고 세미나를 열 만큼 아는 것이 거의 없습니다 ㅎㅎ
저번 프로젝트 때 디자인이 빛났던 @euphony-io/eutamin-c 팀에서 세미나를 열면 좋지 않을까 싶네요!!! 👏👏

**Comment by jopopcorn** [comment]
> 리스트의 각 항목마다 구분이 가게끔 항목의 아래쪽에 옅은 선 같은게 있으면 더 좋을 것 같습니다!

급하게 디자인해서 옅은 선은 생략했는데 개발할 때 구분할 수 있도록 작업하겠습니다! 😹

**Comment by Jsueeee** [comment]
> > 피그마는 UX 디자이너들이 엄청 선호하는 도구던데 잘 사용하시는군여!! 멋집니다 👍
> > 피그마로 협업도 편리한 것 같더라구요. ㅎㅎ 한번 유포니 멘티 대상 피그마 사용 사례 세미나 해보시는건 어떨까여 ㅋㅋ
> 
> ㅋㅋㅋㅋㅋㅋ 저도 아주 간단한 사용법만 알고 있고 세미나를 열 만큼 아는 것이 거의 없습니다 ㅎㅎ
> 저번 프로젝트 때 디자인이 빛났던 @euphony-io/eutamin-c 팀에서 세미나를 열면 좋지 않을까 싶네요!!! 👏👏

아이고 유타민씨팀에서 제가 디자인했었는데, 보통 디자인은 생각만 하고 바로 코드로 짜는 편이어서 저도 피그마를 사용하진 않았습니다 😅 피그마 사용 멋집니다!!👍👍👍

**Comment by jopopcorn** [comment]
> > > 피그마는 UX 디자이너들이 엄청 선호하는 도구던데 잘 사용하시는군여!! 멋집니다 👍
> > > 피그마로 협업도 편리한 것 같더라구요. ㅎㅎ 한번 유포니 멘티 대상 피그마 사용 사례 세미나 해보시는건 어떨까여 ㅋㅋ
> > 
> > 
> > ㅋㅋㅋㅋㅋㅋ 저도 아주 간단한 사용법만 알고 있고 세미나를 열 만큼 아는 것이 거의 없습니다 ㅎㅎ
> > 저번 프로젝트 때 디자인이 빛났던 @euphony-io/eutamin-c 팀에서 세미나를 열면 좋지 않을까 싶네요!!! 👏👏
> 
> 아이고 유타민씨팀에서 제가 디자인했었는데, 보통 디자인은 생각만 하고 바로 코드로 짜는 편이어서 저도 피그마를 사용하진 않았습니다 😅 피그마 사용 멋집니다!!👍👍👍

우와 디자인을 너무 잘하셔서 디자인툴로 미리 밑작업 하신 후에 마크업 하신 줄 알았어요 너무 멋지네요..!! 🥺

**Comment by Jsueeee** [comment]
> > > > 피그마는 UX 디자이너들이 엄청 선호하는 도구던데 잘 사용하시는군여!! 멋집니다 👍
> > > > 피그마로 협업도 편리한 것 같더라구요. ㅎㅎ 한번 유포니 멘티 대상 피그마 사용 사례 세미나 해보시는건 어떨까여 ㅋㅋ
> > > 
> > > 
> > > ㅋㅋㅋㅋㅋㅋ 저도 아주 간단한 사용법만 알고 있고 세미나를 열 만큼 아는 것이 거의 없습니다 ㅎㅎ
> > > 저번 프로젝트 때 디자인이 빛났던 @euphony-io/eutamin-c 팀에서 세미나를 열면 좋지 않을까 싶네요!!! 👏👏
> > 
> > 
> > 아이고 유타민씨팀에서 제가 디자인했었는데, 보통 디자인은 생각만 하고 바로 코드로 짜는 편이어서 저도 피그마를 사용하진 않았습니다 😅 피그마 사용 멋집니다!!👍👍👍
> 
> 우와 디자인을 너무 잘하셔서 디자인툴로 미리 밑작업 하신 후에 마크업 하신 줄 알았어요 너무 멋지네요..!! 🥺

디자인은 간단한데 컬러를 심사숙고해서 고른 게 다행히 효과가 있었나봅니다😆😆ㅋㅋㅋㅋ
사실 피그마를 하나도 몰라서ㅎㅎㅎㅎ 수연님이 더 멋져보이네요!
안그래도 리스너쪽에서 컬러코드 여쭤보려고 했는데, 올려주신 링크 클릭해보니 멤버?같은 게 아니더라도 저도 컬러코드를 볼 수 있네요! 리스너 앱 쪽은 기능구현 먼저 들어가서, 마무리된 다음 디자인을 볼 예정입니다. 스피커 앱과 세트처럼 보이도록 비슷하게 잘 해보겠습니다...!!ㅋㅋㅋㅋ

**Comment by jopopcorn** [comment]
> 디자인은 간단한데 컬러를 심사숙고해서 고른 게 다행히 효과가 있었나봅니다😆😆ㅋㅋㅋㅋ
> 사실 피그마를 하나도 몰라서ㅎㅎㅎㅎ 수연님이 더 멋져보이네요!
> 안그래도 리스너쪽에서 컬러코드 여쭤보려고 했는데, 올려주신 링크 클릭해보니 멤버?같은 게 아니더라도 저도 컬러코드를 볼 수 있네요! 리스너 앱 쪽은 기능구현 먼저 들어가서, 마무리된 다음 디자인을 볼 예정입니다. 스피커 앱과 세트처럼 보이도록 비슷하게 잘 해보겠습니다...!!ㅋㅋㅋㅋ

오오 알겠습니다 피그마를 여기에 공유하길 잘했네요!
혹시라도 디자인 외에 상의할 부분이 생기면 디스커션이나 슬랙 DM으로 바로 말씀드리겠습니다! 😸

**Comment by kmsaidev** [comment]
오오 감사합니다!! 피그마 뭔지 잘 모르는데 한번 사용해보겠습니다~~ 이렇게나마 개발에 참여할 수 있게 되어서 좋습니다🤩🤩

**Comment by kmsaidev** [comment]
@jopopcorn 수연님 거의 다 완성했는데 툴바의 뒤로가기 버튼은 코틀린 파일을 건드려야 할 것 같은데 혹시 xml에서 만드는 방법 알려주실 수 있나요?

**Comment by jopopcorn** [comment]
> @jopopcorn 수연님 거의 다 완성했는데 툴바의 뒤로가기 버튼은 코틀린 파일을 건드려야 할 것 같은데 혹시 xml에서 만드는 방법 알려주실 수 있나요?

툴바의 뒤로가기 버튼은 기본적으로 제공되어 있는데, 그걸 적용하는 방법이 액티비티 코드에 코드 한두줄을 추가하는 것입니다!!
그부분은 제가 작업하려고 했어서 툴바만 배치해주시면 됩니다!
만약 뒤로가기 버튼까지 작업하고 싶으시다면 [이 예제](https://android--code.blogspot.com/2020/06/android-kotlin-toolbar-back-button.html) 읽어보시고 코드 추가하면 될 것 같아요!

**Comment by kmsaidev** [comment]
> > @jopopcorn 수연님 거의 다 완성했는데 툴바의 뒤로가기 버튼은 코틀린 파일을 건드려야 할 것 같은데 혹시 xml에서 만드는 방법 알려주실 수 있나요?
> 
> 툴바의 뒤로가기 버튼은 기본적으로 제공되어 있는데, 그걸 적용하는 방법이 액티비티 코드에 코드 한두줄을 추가하는 것입니다!! 그부분은 제가 작업하려고 했어서 툴바만 배치해주시면 됩니다! 만약 뒤로가기 버튼까지 작업하고 싶으시다면 [이 예제](https://android--code.blogspot.com/2020/06/android-kotlin-toolbar-back-button.html) 읽어보시고 코드 추가하면 될 것 같아요!

넵 감사합니다!!ㅎㅎ
