### ISSUE TITLE
안심번호 입력 다이얼로그 추가 및 SharedPreferences 세팅

### ISSUE THREAD

**Issue by jopopcorn** [euphony-io/check-in-speaker#18]
**Is your feature request related to a problem? Please describe.**
- 안심번호를 입력 받는 다이얼로그 xml 작업
- SharedPreferences에 안심 번호가 저장되어 있지 않은 경우 다이얼로그 띄우기

</br>

**Describe the solution you'd like**
- 안심번호인지 간단하게 체크할 수 있는 로직도 고려하기
- SharedPreferences를 사용하기 위한 Util class 생성

</br>

**Additional Context**
`Main - 첫 실행 (번호 기입 전)`의 화면 참고하여 다이얼로그 마크업하기
안심번호을 입력받으므로 다이얼로그 문구는 "본인의 안심번호를 입력하세요."로 변경하기
<img width="1095" alt="speaker_기본_배치" src="https://user-images.githubusercontent.com/35393459/134714973-8b44b036-4d76-4b4c-a676-bbd0e85d9a2c.png">

**Comment by designe** [comment]
ㅋㅋㅋㅋㅋㅋㅋ 양재시민의숲에서 열시미 개발중이시군여!!

**Comment by jopopcorn** [comment]
> ㅋㅋㅋㅋㅋㅋㅋ 양재시민의숲에서 열시미 개발중이시군여!!

ㅋㅋㅋㅋㅋㅋ 맞습니다~~
