### ISSUE TITLE
앱 아이콘 적용 및 로딩 다이얼로그 변경

### ISSUE THREAD

**Issue by jopopcorn** [euphony-io/check-in-speaker#29]
**Is your feature request related to a problem? Please describe.**
- [x] 앱 아이콘 적용
- [x] 기존 프로그레스바 제거 및 [SpinKit](https://github.com/ybq/Android-SpinKit)로 변경

**Describe the solution you'd like**
SpinKit는 `FadingCircle` style로 적용하기

**Additional context**
리스너 팀과의 [디스커션](https://github.com/euphony-io/check-in-listener/discussions/32)을 참고!

**Comment by psh2849** [comment]
SpinKit를 한번 적용시켜봤는데, 다이얼로그의 색상도 정해야 하는 것 같습니다.

코드 : 
``` kotlin
val fadingCircle: Sprite = FadingCircle()
fadingCircle.color = resources.getColor(R.color.black, null)
binding.progressBarMainCheckin.setIndeterminateDrawable(fadingCircle)
```

결과 : 
![image](https://user-images.githubusercontent.com/42669772/135725416-333b76b8-5293-46ef-b613-5e32fbe6b7e0.png)

**Comment by jopopcorn** [comment]
@psh2849 오오 디테일한 부분을 캐치하셨네요 리스너팀 디스커션에도 올려주시면 좋을 것 같아요!!

**Comment by psh2849** [comment]
> @psh2849 오오 디테일한 부분을 캐치하셨네요 리스너팀 디스커션에도 올려주시면 좋을 것 같아요!!

앱 아이콘도 결정나면 제가 수정하고 PR 올리겠습니다!

**Comment by jopopcorn** [comment]
> > @psh2849 오오 디테일한 부분을 캐치하셨네요 리스너팀 디스커션에도 올려주시면 좋을 것 같아요!!
> 
> 앱 아이콘도 결정나면 제가 수정하고 PR 올리겠습니다!

넵넵 좋습니다!!
